import type { Metadata } from "next";
import Nav from "@/components/Nav";
import "../style/main.scss";
import { myFont } from "@/fonts/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={myFont.className}>
			<body>
				<Nav />
				{children}
			</body>
		</html>
	);
}
